### ISSUE TITLE
FreeCAD Path Workbench for CAM?

### ISSUE THREAD

**Issue by eduncan911** [MakeraInc/CarveraProfiles#1]
Hello: I would like to help with any FreeCAD integration with its CAM software for the Carvera.  Including the tool changing and 4th axis rotary.

Would this be something Carvera is interested in?

**Comment by greggjaskiewicz** [comment]
I asked Makera for some help here, I'm willing to put time. Standby. (don't have the machine [yet]) tho!

**Comment by eduncan911** [comment]
Closing as my buddy has completed this, with zero Carvera help.  Bypasses their software and has full paths now.

I'm trying to get him to publish it on Github so people are not locked into proprietary software.  

Until then, closing this ticket as Carvera provided zero help after ghosting my email conversation we had back and forth.  Where it could have helped them, now it will hurt them by releasing for free.
